//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_author
    {
        public int id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> author_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual book book { get; set; }
    }
}
