//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrow
    {
        public int id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public Nullable<System.DateTime> returned_date { get; set; }
    
        public virtual book book { get; set; }
        public virtual member member { get; set; }
    }
}
